export const ADD_COMBINATION = 'ADD_COMBINATION'
export const ADD_STANDINGS_TO_COMBINATION = 'ADD_STANDINGS_TO_COMBINATION'
export const ADD_OTHER_STANDINGS_TO_COMBINATION = 'ADD_OTHER_STANDINGS_TO_COMBINATION'
export const MARK_COMBINATIONS_SAVED = 'MARK_COMBINATIONS_SAVED'